import { useEffect, useMemo, useState } from 'react'
import { ArrowLeft, BarChart3, BookOpen, Check, CircleAlert, Clock3, Crown, Gift, Info, LockKeyhole, Medal, NotebookPen, Orbit, RefreshCw, Rocket, Settings, ShieldCheck, Sparkles, Star, Trash2, Trophy, X } from 'lucide-react'
import { booths, teams, teamById, scoreConfig, loadStaticConfig } from './data'

const emptyState={version:1,booths:{}}
const defaultRound={status:'waiting',scores:{},mvp:'',notes:'',sessions:{}}
const clone=v=>JSON.parse(JSON.stringify(v))
const numeric=v=>Math.max(0,Number(v)||0)
const teamScore=(scores,teamId,categories)=>{const value=scores?.[teamId];if(value&&typeof value==='object')return categories.reduce((n,c)=>n+numeric(value[c.id]),0);return numeric(value)}
function Starfield(){return <div className="starfield" aria-hidden="true"><i/><i/><i/></div>}
function Brand(){return <div className="brand"><span className="brand-mark"><Star size={17} fill="currentColor"/></span><span><b>D:FORCE</b><small>2026 SUMMER CAMP</small></span></div>}

export default function App(){
  const [route,setRoute]=useState({page:'home'}),[live,setLive]=useState(emptyState),[online,setOnline]=useState(true),[toast,setToast]=useState(''),[config,setConfig]=useState({ready:false,error:''}),[gate,setGate]=useState(null)
  const load=async()=>{try{const r=await fetch('/.netlify/functions/state',{cache:'no-store'});if(!r.ok)throw Error();setLive(await r.json());setOnline(true)}catch{setOnline(false);const saved=localStorage.getItem('dforce-state');if(saved)setLive(JSON.parse(saved))}}
  useEffect(()=>{loadStaticConfig().then(()=>setConfig({ready:true,error:''})).catch(e=>setConfig({ready:false,error:e.message}));load();const id=setInterval(load,2000);return()=>clearInterval(id)},[])
  const save=async next=>{setLive(next);localStorage.setItem('dforce-state',JSON.stringify(next));try{const r=await fetch('/.netlify/functions/state',{method:'POST',headers:{'content-type':'application/json'},body:JSON.stringify(next)});if(!r.ok)throw Error();setLive(await r.json());setOnline(true)}catch{setOnline(false)}}
  const updateRound=(boothId,roundId,fn)=>{const next=clone(live);next.booths??={};next.booths[boothId]??={};next.booths[boothId][roundId]=fn({...defaultRound,...next.booths[boothId][roundId]});save(next)}
  const notify=t=>{setToast(t);setTimeout(()=>setToast(''),2200)}
  const protectedGo=target=>setGate(target)
  if(config.error)return <main><Starfield/><div className="config-error"><CircleAlert/><h1>설정 파일을 확인해 주세요</h1><p>{config.error}</p><button onClick={()=>location.reload()}><RefreshCw/> 다시 불러오기</button></div></main>
  if(!config.ready)return <main><Starfield/><div className="loading"><Orbit/><b>우주 탐험대 준비 중…</b></div></main>
  const booth=booths.find(b=>b.id===route.booth)
  return <main><Starfield/><header><Brand/><div className="header-actions">{route.page==='home'&&<button className="admin-button" onClick={()=>protectedGo({page:'admin'})}><Settings/>관리자</button>}<span className={`sync ${online?'ok':''}`}><i/>{online?'LIVE':'OFFLINE'}</span></div></header>
    {route.page==='home'?<Home enter={(b,role)=>role==='score'?protectedGo({page:'booth',booth:b.id,role,round:'r1'}):setRoute({page:'booth',booth:b.id,role,round:'r1'})}/>:
     route.page==='admin'?<Admin live={live} save={save} setRoute={setRoute} notify={notify}/>:
     <Booth booth={booth} route={route} setRoute={setRoute} protectedGo={protectedGo} live={live} updateRound={updateRound} notify={notify}/>} 
    {gate&&<PinGate cancel={()=>setGate(null)} success={()=>{setRoute(gate);setGate(null)}}/>}{toast&&<div className="toast"><Check size={18}/>{toast}</div>}
  </main>
}

function PinGate({cancel,success}){const [pin,setPin]=useState(''),[error,setError]=useState(false);const submit=e=>{e.preventDefault();if(pin==='1111')success();else{setPin('');setError(true)}};return <Modal close={cancel}><form className="pin-gate" onSubmit={submit}><span className="modal-icon"><LockKeyhole/></span><p className="eyebrow">AUTHORIZED CREW ONLY</p><h2>접근 비밀번호</h2><p>점수판과 관리자 기능은 운영 선생님만 사용할 수 있습니다.</p><input autoFocus type="password" inputMode="numeric" maxLength="4" value={pin} onChange={e=>{setPin(e.target.value);setError(false)}} placeholder="••••"/><small className={error?'show':''}>비밀번호가 올바르지 않습니다.</small><button className="primary wide" type="submit"><ShieldCheck/> 확인</button></form></Modal>}

function Home({enter}){return <section className="home shell"><div className="hero"><div className="orbit-hero"><div className="planet"><Rocket/></div><span/><span/><span/></div><p className="eyebrow">ORBITAL MISSION CONTROL</p><h1>하나님의 꿈을 향한<br/><em>우주 탐험대</em></h1><p>선생님의 땀방울이 아이들의 별빛이 됩니다.<br/>운영할 게임 부스를 선택해 주세요.</p></div><div className="booth-grid">{booths.map((b,i)=><article className="booth-card" key={b.id} style={{'--accent':b.accent,'--delay':`${i*.08}s`}}><div className="card-space"><span className="booth-code">MISSION {b.id}</span><div className="game-orb">{b.icon}</div><h2>{b.title}</h2><p>{b.short}</p><small>{b.verse}</small></div><div className="role-row"><button onClick={()=>enter(b,'score')}><BarChart3/>점수판</button><button className="ghost" onClick={()=>enter(b,'mission')}><Rocket/>미션판</button></div></article>)}</div><footer>동탄동산교회 디포스 초등부 여름캠프 · 나는 하나님의 꿈이야!</footer></section>}

function Booth({booth,route,setRoute,protectedGo,live,updateRound,notify}){const [info,setInfo]=useState(false),[roundId,setRoundId]=useState(route.round||'r1');const round=booth.rounds.find(r=>r.id===roundId),data={...defaultRound,...live.booths?.[booth.id]?.[roundId]};return <section className="booth-page shell" style={{'--accent':booth.accent}}><nav className="topnav"><button className="icon-btn" onClick={()=>setRoute({page:'home'})}><ArrowLeft/></button><div><span>MISSION {booth.id}</span><b>{booth.title}</b></div><button className="icon-btn" onClick={()=>setInfo(true)}><Info/></button></nav><div className="mission-head"><div className="mission-orb">{booth.icon}</div><div><p>{booth.short}</p><h1>{booth.title}</h1><span><BookOpen/> {booth.verse}</span></div></div><div className="round-tabs">{booth.rounds.map(r=><button key={r.id} className={roundId===r.id?'active':''} onClick={()=>setRoundId(r.id)}><small>{r.time}</small><b>{r.label}</b><i className={live.booths?.[booth.id]?.[r.id]?.status||'waiting'}/></button>)}</div><Matchup round={round} status={data.status}/>{route.role==='score'?<ScoreBoard booth={booth} round={round} data={data} update={fn=>updateRound(booth.id,roundId,fn)} notify={notify}/>:<MissionBoard booth={booth} round={round} data={data} update={fn=>updateRound(booth.id,roundId,fn)} notify={notify}/>}<button className="mode-switch" onClick={()=>route.role==='mission'?protectedGo({...route,role:'score'}):setRoute({...route,role:'mission'})}>{route.role==='score'?<Rocket/>:<BarChart3/>}{route.role==='score'?'미션판 보기':'점수판 보기'}</button>{info&&<Modal close={()=>setInfo(false)}><div className="info-modal"><span className="modal-icon"><BookOpen/></span><p className="eyebrow">GAME BRIEFING</p><h2>{booth.title}</h2><blockquote>{booth.theme}</blockquote><h3>게임 진행</h3><p>{booth.guide}</p><h3><CircleAlert/> 안전 주의사항</h3><p>{booth.caution}</p></div></Modal>}</section>}

function Matchup({round,status}){const a=teamById[round.teams[0]],b=teamById[round.teams[1]];return <div className="matchup"><div className="team-badge" style={{'--team':a.color}}><i/><b>{a.name}</b></div><div className="versus"><span className={`status-dot ${status}`}>{status==='active'?'진행 중':status==='done'?'완료':'대기'}</span><strong>VS</strong><small>{round.time}</small></div><div className="team-badge right" style={{'--team':b.color}}><i/><b>{b.name}</b></div></div>}

function ScoreBoard({booth,round,data,update,notify}){const pair=round.teams.map(id=>teamById[id]),cats=scoreConfig[booth.id];const normalize=()=>{const scores={};for(const t of pair){const old=data.scores?.[t.id];scores[t.id]=old&&typeof old==='object'?old:{game:numeric(old)}}return scores};const [local,setLocal]=useState({scores:normalize(),mvp:data.mvp||'',notes:data.notes||''});useEffect(()=>setLocal({scores:normalize(),mvp:data.mvp||'',notes:data.notes||''}),[round.id,data.mvp,data.notes,JSON.stringify(data.scores)]);const setScore=(teamId,cat,value)=>setLocal({...local,scores:{...local.scores,[teamId]:{...local.scores[teamId],[cat.id]:Math.min(cat.max,numeric(value))}}});const persist=()=>{update(d=>({...d,...local}));notify('점수판을 저장했어요')};const sessions=Object.entries(data.sessions||{}).filter(([,s])=>s.missionId);return <div className="control-panel"><div className="panel-title"><span><BarChart3/> SCORE CONTROL</span><b>라운드 점수판</b></div><div className="status-controls">{[['waiting','대기'],['active','진행'],['done','완료']].map(([id,label])=><button key={id} className={data.status===id?'active':''} onClick={()=>update(d=>({...d,status:id}))}>{label}</button>)}</div><div className="detailed-score-grid">{pair.map(t=><section className="detailed-score" key={t.id} style={{'--team':t.color}}><header><i/><b>{t.name}</b><strong>{teamScore(local.scores,t.id,cats)}점</strong></header>{cats.map(c=><label key={c.id}><span>{c.label}<small>/{c.max}</small></span><input type="number" inputMode="numeric" min="0" max={c.max} value={local.scores[t.id]?.[c.id]??''} placeholder="0" onChange={e=>setScore(t.id,c,e.target.value)}/></label>)}</section>)}</div><div className="field"><label><Medal/> MVP 학생</label><input value={local.mvp} onChange={e=>setLocal({...local,mvp:e.target.value})} placeholder="이름을 입력하세요"/></div><div className="field"><label><NotebookPen/> 기타 기록</label><textarea value={local.notes} onChange={e=>setLocal({...local,notes:e.target.value})} placeholder="특이사항과 점수 근거를 기록하세요"/></div><button className="primary wide" onClick={persist}><Check/> 점수판 저장</button><div className="approval"><div className="panel-title"><span><Sparkles/> MISSION REQUEST</span><b>미션 승인</b></div>{sessions.length===0?<div className="empty"><Orbit/><p>미션판에서 미션을 뽑으면<br/>여기에 승인 요청이 나타납니다.</p></div>:sessions.map(([teamId,s])=><Request key={teamId} team={teamById[teamId]} session={s} booth={booth} update={update}/>)}</div></div>}

function Request({team,session,booth,update}){const mission=booth.missions.find(m=>m.id===session.missionId),item=booth.items.find(i=>i.id===session.itemId);return <div className="request" style={{'--team':team.color}}><div><span>{team.name}</span><b>{mission?.title}</b><p>{mission?.description}</p></div>{session.itemId?<div className="awarded"><Gift/><span><small>획득 아이템</small><b>{item?.title}</b></span>{session.used?<em>사용 완료</em>:<button onClick={()=>update(d=>({...d,sessions:{...d.sessions,[team.id]:{...session,used:true,usedAt:Date.now()}}}))}>사용 완료</button>}</div>:session.approved?<span className="waiting-box">미션판에서 상자를 여는 중…</span>:<div className="request-actions"><button className="reject" onClick={()=>update(d=>({...d,sessions:{...d.sessions,[team.id]:{}}}))}><RefreshCw/> 다시</button><button className="approve" onClick={()=>update(d=>({...d,sessions:{...d.sessions,[team.id]:{...session,approved:true}}}))}><Check/> 승인</button></div>}</div>}

function MissionBoard({booth,round,data,update,notify}){const [teamId,setTeamId]=useState(round.teams[0]),[rolling,setRolling]=useState(false),[opening,setOpening]=useState(false);useEffect(()=>setTeamId(round.teams[0]),[round.id]);const team=teamById[teamId],session=data.sessions?.[teamId]||{},mission=booth.missions.find(m=>m.id===session.missionId),item=booth.items.find(i=>i.id===session.itemId);const drawMission=()=>{setRolling(true);setTimeout(()=>{const m=booth.missions[Math.floor(Math.random()*booth.missions.length)];update(d=>({...d,sessions:{...d.sessions,[teamId]:{missionId:m.id,approved:false}}}));setRolling(false)},1400)};const openBox=()=>{setOpening(true);setTimeout(()=>{const won=weighted(booth.items);update(d=>({...d,sessions:{...d.sessions,[teamId]:{...session,itemId:won.id,awardedAt:Date.now()}}}));setOpening(false);notify('새 아이템을 획득했어요!')},1700)};return <div className="student-panel" style={{'--team':team.color}}><div className="team-switch">{round.teams.map(id=><button className={teamId===id?'active':''} key={id} style={{'--team':teamById[id].color}} onClick={()=>setTeamId(id)}><i/>{teamById[id].name}</button>)}</div><div className="student-stage"><p className="eyebrow">PLAYER MISSION BOARD</p><h2>{team.name} 탐험대</h2>{!session.missionId?<div className={`holo-card ${rolling?'rolling':''}`}><div><Sparkles/><b>{rolling?'미션 탐색 중…':'랜덤 미션 카드'}</b><small>우주의 카드를 터치해 보세요</small></div></div>:<MissionCard mission={mission} approved={session.approved}/>} {!session.missionId&&<button className="primary launch" disabled={rolling||data.status!=='active'} onClick={drawMission}><Orbit/>{data.status==='active'?'랜덤 보드 돌리기':'점수판에서 라운드를 시작하면 열려요'}</button>}{session.missionId&&!session.approved&&!session.itemId&&<div className="approval-wait"><Clock3/><b>선생님 승인을 기다리고 있어요</b><span>미션을 멋지게 수행해 주세요!</span></div>}{session.approved&&!session.itemId&&<button className={`loot-box ${opening?'opening':''}`} onClick={openBox} disabled={opening}><Gift/><b>{opening?'별빛 에너지 충전 중…':'아이템 상자 열기'}</b><small>터치해서 보상을 확인하세요</small></button>}{item&&<ItemReveal item={item} used={session.used}/>} {session.itemId&&<button className="secondary" onClick={()=>update(d=>({...d,sessions:{...d.sessions,[teamId]:{}}}))}><RefreshCw/> 다음 미션 준비</button>}</div></div>}

function Admin({live,save,setRoute,notify}){const [tab,setTab]=useState('score'),[game,setGame]=useState('A');const reset=(scope,type)=>{const label=scope==='all'?'전체 게임':`게임 ${scope}`;if(!confirm(`${label}의 ${type==='score'?'점수':'미션'} 기록을 리셋할까요?`))return;if(!confirm('이 작업은 되돌릴 수 없습니다. 정말 진행할까요?'))return;const next=clone(live);const targets=scope==='all'?booths.map(b=>b.id):[scope];for(const id of targets){next.booths??={};next.booths[id]??={};for(const r of booths.find(b=>b.id===id).rounds){const d={...defaultRound,...next.booths[id][r.id]};if(type==='score'){d.scores={};d.mvp='';d.notes=''}else d.sessions={};next.booths[id][r.id]=d}}save(next);notify(`${label} ${type==='score'?'점수':'미션'} 기록을 초기화했어요`)};return <section className="admin-page shell"><nav className="topnav"><button className="icon-btn" onClick={()=>setRoute({page:'home'})}><ArrowLeft/></button><div><span>MASTER CONTROL</span><b>운영 관리자</b></div><span className="admin-crown"><Crown/></span></nav><div className="admin-tabs"><button className={tab==='score'?'active':''} onClick={()=>setTab('score')}><Trophy/>점수판</button><button className={tab==='mission'?'active':''} onClick={()=>setTab('mission')}><Rocket/>미션판</button></div><div className="admin-games">{booths.map(b=><button key={b.id} className={game===b.id?'active':''} style={{'--accent':b.accent}} onClick={()=>setGame(b.id)}>{b.id}</button>)}</div>{tab==='score'?<AdminScores live={live} game={game} reset={reset}/>:<AdminMissions live={live} game={game} reset={reset}/>}</section>}

function AdminScores({live,game,reset}){const gameRanks=rankForGame(live,game),overall=rankOverall(live);return <div className="admin-content"><Ranking title={`게임 ${game} 실시간 랭킹`} rows={gameRanks}/><Ranking title="전체 합산 랭킹" rows={overall}/><div className="reset-zone"><button onClick={()=>reset(game,'score')}><Trash2/>게임 {game} 점수 리셋</button><button className="danger" onClick={()=>reset('all','score')}><Trash2/>전체 점수 리셋</button></div></div>}
function AdminMissions({live,game,reset}){const booth=booths.find(b=>b.id===game),stats=teams.map(t=>{let drawn=0,approved=0,awarded=0,used=0;for(const r of booth.rounds){const s=live.booths?.[game]?.[r.id]?.sessions?.[t.id];if(s?.missionId)drawn++;if(s?.approved)approved++;if(s?.itemId)awarded++;if(s?.used)used++}return {...t,drawn,approved,awarded,used}}).filter(x=>x.drawn);return <div className="admin-content"><section className="admin-card"><h2>게임 {game} 미션 수행 현황</h2>{!stats.length?<div className="empty"><Orbit/><p>아직 수행 중인 미션이 없습니다.</p></div>:stats.map(s=><div className="mission-stat" key={s.id} style={{'--team':s.color}}><i/><b>{s.name}</b><span>추첨 {s.drawn}</span><span>승인 {s.approved}</span><span>획득 {s.awarded}</span><span>사용 {s.used}</span></div>)}</section><div className="reset-zone"><button onClick={()=>reset(game,'mission')}><Trash2/>게임 {game} 미션 리셋</button><button className="danger" onClick={()=>reset('all','mission')}><Trash2/>전체 미션 리셋</button></div></div>}
function Ranking({title,rows}){return <section className="admin-card"><h2>{title}</h2>{rows.map((r,i)=><div className="rank-row" key={r.id} style={{'--team':r.color}}><strong>{i+1}</strong><i/><b>{r.name}</b><span>{r.score}점</span></div>)}</section>}
function rankForGame(live,id){const b=booths.find(x=>x.id===id),cats=scoreConfig[id];return teams.map(t=>({...t,score:b.rounds.reduce((n,r)=>n+teamScore(live.booths?.[id]?.[r.id]?.scores,t.id,cats),0)})).sort((a,b)=>b.score-a.score)}
function rankOverall(live){return teams.map(t=>({...t,score:booths.reduce((n,b)=>n+rankForGame(live,b.id).find(x=>x.id===t.id).score,0)})).sort((a,b)=>b.score-a.score)}
function MissionCard({mission,approved}){return <div className={`mission-card ${approved?'approved':''}`}><div className="card-top"><span>MISSION {mission.id.padStart(2,'0')}</span>{approved&&<em><Check/> 승인 완료</em>}</div><div className="mission-symbol"><Star/></div><h3>{mission.title}</h3><p>{mission.description}</p></div>}
function ItemReveal({item,used}){return <div className={`item-reveal ${used?'used':''}`}><span className="rarity">STAR ITEM</span><div className="item-gem"><Gift/></div><p>ITEM {item.id.padStart(2,'0')}</p><h3>{item.title}</h3><div>{item.description}</div>{used&&<em><Check/> 사용 완료</em>}</div>}
function Modal({children,close}){return <div className="modal" onClick={close}><div className="modal-body" onClick={e=>e.stopPropagation()}><button className="modal-close" onClick={close}><X/></button>{children}</div></div>}
function weighted(items){const total=items.reduce((n,i)=>n+i.weight,0);let r=Math.random()*total;return items.find(i=>(r-=i.weight)<=0)||items[0]}
