import { useEffect, useMemo, useRef, useState } from 'react'
import { ArrowLeft, BarChart3, BookOpen, Check, CircleAlert, Clock3, Crown, Gift, Info, LayoutDashboard, LockKeyhole, Medal, NotebookPen, Orbit, RefreshCw, Rocket, Settings, ShieldCheck, Sparkles, Star, Trash2, Trophy, X } from 'lucide-react'
import { booths, teams, teamById, scoreConfig, scheduleBreaks, loadStaticConfig } from './data'
import './operations.css'

const emptyState={version:1,booths:{}}
const defaultRound={status:'waiting',scores:{},mvp:'',mvpTeam:'',mvps:{},notes:'',notesByTeam:{},sessions:{},missionLogs:{},missionPresets:{}}
const clone=v=>JSON.parse(JSON.stringify(v))
const numeric=v=>Math.max(0,Number(v)||0)
const teamScore=(scores,teamId,categories)=>{const value=scores?.[teamId];if(value&&typeof value==='object')return categories.reduce((n,c)=>n+numeric(value[c.id]),0);return numeric(value)}
const roundTime=(live,round)=>live.scheduleTimes?.[round.id]||round.time
let currentGameLocations={}
function nextStop(teamId,boothId,roundId){const booth=booths.find(b=>b.id===boothId),index=booth.rounds.findIndex(r=>r.id===roundId),nextRound=booth.rounds[index+1];if(!nextRound)return null;const nextBooth=booths.find(b=>b.rounds.find(r=>r.id===nextRound.id)?.teams.includes(teamId));return nextBooth?{booth:nextBooth,round:nextRound,location:currentGameLocations[nextBooth.id]||'장소 미정'}:null}
function Starfield(){return <div className="starfield" aria-hidden="true"><i/><i/><i/></div>}
function Brand({onHome}){return <button type="button" className="brand" onClick={onHome} aria-label="홈으로 이동"><span className="brand-mark"><Star size={17} fill="currentColor"/></span><span><b>D:FORCE</b><small>2026 SUMMER CAMP</small></span></button>}

export default function App(){
  const [route,setRoute]=useState({page:'home'}),[live,setLive]=useState(emptyState),[online,setOnline]=useState(true),[toast,setToast]=useState(''),[config,setConfig]=useState({ready:false,error:''}),[gate,setGate]=useState(null)
  const latestRef=useRef(emptyState),mutationEpoch=useRef(0),pendingWrites=useRef(0),lastVersion=useRef(0),writeChain=useRef(Promise.resolve())
  const applyLive=state=>{latestRef.current=state;lastVersion.current=Math.max(lastVersion.current,Number(state.version)||0);setLive(state)}
  const load=async()=>{const startedEpoch=mutationEpoch.current;try{const r=await fetch('/.netlify/functions/state',{cache:'no-store'});if(!r.ok)throw Error();const state=await r.json();if(startedEpoch!==mutationEpoch.current||pendingWrites.current>0||(Number(state.version)||0)<lastVersion.current)return;applyLive(state);setOnline(true)}catch{setOnline(false);const saved=localStorage.getItem('dforce-state');if(saved&&!Object.keys(latestRef.current.booths||{}).length)applyLive(JSON.parse(saved))}}
  useEffect(()=>{loadStaticConfig().then(()=>setConfig({ready:true,error:''})).catch(e=>setConfig({ready:false,error:e.message}));load();const id=setInterval(load,2000);return()=>clearInterval(id)},[])
  useEffect(()=>{if(route.page!=='admin')return;const id=setTimeout(()=>{const input=document.querySelector('.full-reset input');if(input)input.placeholder='비밀번호 4자리 입력'},0);return()=>clearTimeout(id)},[route.page])
  const save=next=>{const epoch=++mutationEpoch.current;pendingWrites.current++;applyLive(next);localStorage.setItem('dforce-state',JSON.stringify(next));writeChain.current=writeChain.current.then(async()=>{try{const r=await fetch('/.netlify/functions/state',{method:'POST',headers:{'content-type':'application/json'},body:JSON.stringify(next)});if(!r.ok)throw Error();const saved=await r.json();if(epoch===mutationEpoch.current)applyLive(saved);setOnline(true)}catch{setOnline(false)}finally{pendingWrites.current--}});return writeChain.current}
  const updateRound=(boothId,roundId,fn)=>{const next=clone(latestRef.current);next.booths??={};next.booths[boothId]??={};const current={...defaultRound,...next.booths[boothId][roundId]},updated=fn(current);if(updated.status==='active'&&current.status!=='active'){const booth=booths.find(b=>b.id===boothId),other=booth.rounds.find(r=>r.id!==roundId&&next.booths[boothId][r.id]?.status==='active');if(other){alert(`${other.label}이 진행중입니다.`);return}const index=booth.rounds.findIndex(r=>r.id===roundId),incomplete=booth.rounds.slice(0,index).find(r=>(next.booths[boothId][r.id]?.status||'waiting')!=='done');if(incomplete){alert(`${incomplete.label}을 먼저 완료해 주세요.`);return}}next.booths[boothId][roundId]=updated;save(next)}
  const notify=t=>{setToast(t);setTimeout(()=>setToast(''),2200)}
  const protectedGo=target=>setGate(target)
  if(config.error)return <main><Starfield/><div className="config-error"><CircleAlert/><h1>설정 파일을 확인해 주세요</h1><p>{config.error}</p><button onClick={()=>location.reload()}><RefreshCw/> 다시 불러오기</button></div></main>
  if(!config.ready)return <main><Starfield/><div className="loading"><Orbit/><b>우주 탐험대 준비 중…</b></div></main>
  currentGameLocations=live.gameLocations||{}
  const booth=booths.find(b=>b.id===route.booth)
  return <main><Starfield/><header><Brand onHome={()=>setRoute({page:'home'})}/><div className="header-actions">{route.page==='home'&&<button className="admin-button" onClick={()=>protectedGo({page:'admin'})}><Settings/>관리자</button>}<span className={`sync ${online?'ok':''}`}><i/>{online?'LIVE':'OFFLINE'}</span></div></header>
    {route.page==='home'?<Home enter={(b,role)=>role==='score'?protectedGo({page:'booth',booth:b.id,role,round:'r1'}):setRoute({page:'booth',booth:b.id,role,round:'r1'})}/>:
     route.page==='admin'?<Admin live={live} save={save} setRoute={setRoute} notify={notify}/>:
     <Booth booth={booth} route={route} setRoute={setRoute} protectedGo={protectedGo} live={live} updateRound={updateRound} notify={notify}/>} 
    {gate&&<PinGate cancel={()=>setGate(null)} success={()=>{setRoute(gate);setGate(null)}}/>}{toast&&<div className="toast"><Check size={18}/>{toast}</div>}
  </main>
}

function PinGate({cancel,success}){const [pin,setPin]=useState(''),[error,setError]=useState(false);const submit=e=>{e.preventDefault();if(pin==='1111')success();else{setPin('');setError(true)}};return <Modal close={cancel}><form className="pin-gate" onSubmit={submit}><span className="modal-icon"><LockKeyhole/></span><p className="eyebrow">AUTHORIZED CREW ONLY</p><h2>접근 비밀번호</h2><p>점수판과 관리자 기능은 운영 선생님만 사용할 수 있습니다.</p><input autoFocus type="password" inputMode="numeric" maxLength="4" value={pin} onChange={e=>{setPin(e.target.value);setError(false)}} placeholder="••••"/><small className={error?'show':''}>비밀번호가 올바르지 않습니다.</small><kbd className="enter-hint">↵ Enter 키로 확인</kbd><button className="primary wide" type="submit"><ShieldCheck/> 확인</button></form></Modal>}

function Home({enter}){return <section className="home shell"><div className="hero"><div className="orbit-hero"><div className="planet"><Rocket/></div><span/><span/><span/></div><p className="eyebrow">ORBITAL MISSION CONTROL</p><h1>하나님의 꿈을 향한<br/><em>우주 탐험대</em></h1><p>선생님의 땀방울이 아이들의 별빛이 됩니다.<br/>운영할 게임 부스를 선택해 주세요.</p></div><div className="booth-grid">{booths.map((b,i)=><article className="booth-card" key={b.id} style={{'--accent':b.accent,'--delay':`${i*.08}s`}}><div className="card-space"><span className="booth-code">MISSION {b.id}</span><div className="game-orb">{b.icon}</div><h2>{b.title}</h2><p>{b.short}</p><small>{b.verse}</small></div><div className="role-row"><button onClick={()=>enter(b,'score')}><BarChart3/>점수판</button><button className="ghost" onClick={()=>enter(b,'mission')}><Rocket/>미션판</button></div></article>)}</div><footer>동탄동산교회 디포스 초등부 여름캠프 · 나는 하나님의 꿈이야!</footer></section>}

function Booth({booth,route,setRoute,protectedGo,live,updateRound,notify}){const [info,setInfo]=useState(false),[roundId,setRoundId]=useState(route.round||'r1'),boothState=live.booths?.[booth.id]||{},activeRound=booth.rounds.find(r=>boothState[r.id]?.status==='active');useEffect(()=>{if(route.role==='mission'&&activeRound&&activeRound.id!==roundId)setRoundId(activeRound.id)},[route.role,activeRound?.id]);const round=booth.rounds.find(r=>r.id===roundId),data={...defaultRound,...boothState[roundId]};return <section className="booth-page shell" style={{'--accent':booth.accent}}><nav className="topnav"><button className="icon-btn" onClick={()=>setRoute({page:'home'})}><ArrowLeft/></button><div><span>MISSION {booth.id}</span><b>{booth.title}</b></div><button className="icon-btn" onClick={()=>setInfo(true)}><Info/></button></nav><div className="mission-head"><div className="mission-orb">{booth.icon}</div><div><p>{booth.short}</p><h1>{booth.title}</h1><span><BookOpen/> {booth.verse}</span></div></div><div className="round-tabs">{booth.rounds.map(r=>{const status=boothState[r.id]?.status||'waiting',locked=route.role==='mission'&&status!=='active';return <button key={r.id} disabled={locked} className={`${roundId===r.id?'active':''} ${locked?'locked':''}`} onClick={()=>setRoundId(r.id)}><small>{roundTime(live,r)}</small><b>{r.label}</b><i className={status}/></button>})}</div>{route.role==='score'&&live.moveAlert&&<div className="move-alert"><Rocket/><div><b>이동하세요!</b><span>팀명을 눌러 다음 게임 장소를 확인해 주세요.</span></div></div>}<Matchup booth={booth} round={round} status={data.status} time={roundTime(live,round)}/>{route.role==='score'?<ScoreBoard booth={booth} round={round} data={data} boothState={boothState} update={fn=>updateRound(booth.id,roundId,fn)} notify={notify}/>:<MissionBoard booth={booth} round={round} data={data} update={fn=>updateRound(booth.id,roundId,fn)} notify={notify}/>}<button className="mode-switch" onClick={()=>route.role==='mission'?protectedGo({...route,role:'score'}):setRoute({...route,role:'mission'})}>{route.role==='score'?<Rocket/>:<BarChart3/>}{route.role==='score'?'미션판 보기':'점수판 보기'}</button>{info&&<Modal close={()=>setInfo(false)}><GameInfo booth={booth}/></Modal>}</section>}

function GameInfo({booth}){const d=booth.details;return <div className="info-modal"><span className="modal-icon"><BookOpen/></span><p className="eyebrow">GAME BRIEFING</p><h2>{d.title}</h2><InfoSection title="성경 말씀 베이스" text={d.scriptureBase}/><InfoSection title="영적 교육 목표" text={d.spiritualGoal}/><InfoSection title="행동/실행 목표" text={d.actionGoal}/><section className="detail-section"><h3>게임 세부 규칙</h3><ol>{d.rules.map((rule,i)=><li key={i}>{rule}</li>)}</ol></section><InfoSection title="소요 예산 및 준비물" text={d.budgetAndSupplies}/><InfoSection title="교사 진행 가이드 팁" text={d.teacherTips}/></div>}
function InfoSection({title,text}){return <section className="detail-section"><h3>{title}</h3><p>{text}</p></section>}

function Matchup({booth,round,status,time}){const [selected,setSelected]=useState(null),a=teamById[round.teams[0]],b=teamById[round.teams[1]];return <><div className="matchup"><button className="team-badge" style={{'--team':a.color}} onClick={()=>setSelected(a)}><i/><b>{a.name}</b></button><div className="versus"><span className={`status-dot ${status}`}>{status==='active'?'진행 중':status==='done'?'완료':'대기'}</span><strong>VS</strong><small>{time}</small></div><button className="team-badge right" style={{'--team':b.color}} onClick={()=>setSelected(b)}><i/><b>{b.name}</b></button></div>{selected&&<TeamRoute team={selected} booth={booth} round={round} close={()=>setSelected(null)}/>}</>}
function TeamRoute({team,booth,round,close}){const next=nextStop(team.id,booth.id,round.id);return <Modal close={close}><div className="team-route" style={{'--team':team.color}}><span className="modal-icon"><Rocket/></span><p className="eyebrow">NEXT MISSION</p><h2>{team.name} 이동 안내</h2><div><section><small>현재 게임</small><b>GAME {booth.id}</b><span>{booth.title}</span></section><strong>→</strong><section><small>다음 게임</small>{next?<><b>GAME {next.booth.id}</b><span>{next.booth.title}</span><em>{next.round.label}</em><mark>{next.location}</mark></>:<><b>일정 완료</b><span>모든 게임을 마쳤습니다!</span></>}</section></div></div></Modal>}

function ScoreBoard({booth,round,data,update,notify}){const pair=round.teams.map(id=>teamById[id]),cats=scoreConfig[booth.id];const normalizeScores=()=>Object.fromEntries(pair.map(t=>{const old=data.scores?.[t.id];return [t.id,old&&typeof old==='object'?old:{game:numeric(old)}]}));const normalizeMvps=()=>{const mvps={...data.mvps};if(data.mvp&&data.mvpTeam&&!mvps[data.mvpTeam])mvps[data.mvpTeam]=data.mvp;return mvps};const normalizeNotes=()=>{const notes={...data.notesByTeam};if(data.notes&&!Object.values(notes).some(Boolean))for(const t of pair)notes[t.id]=data.notes;return notes};const [local,setLocal]=useState({scores:normalizeScores(),mvps:normalizeMvps(),notesByTeam:normalizeNotes()});useEffect(()=>setLocal({scores:normalizeScores(),mvps:normalizeMvps(),notesByTeam:normalizeNotes()}),[round.id,data.mvp,data.mvpTeam,data.notes,JSON.stringify(data.mvps),JSON.stringify(data.notesByTeam),JSON.stringify(data.scores)]);const setScore=(teamId,cat,value)=>setLocal(v=>({...v,scores:{...v.scores,[teamId]:{...v.scores[teamId],[cat.id]:Math.min(cat.max,Math.max(0,numeric(value)))}}}));const bump=(teamId,cat,delta)=>setScore(teamId,cat,numeric(local.scores[teamId]?.[cat.id])+delta);const persist=()=>{update(d=>({...d,...local,mvp:'',mvpTeam:'',notes:''}));notify('점수판을 저장했어요')};const resetMissions=()=>{if(!confirm('이 라운드의 모든 미션과 아이템 기록을 리셋할까요?'))return;if(!confirm('삭제된 기록은 되돌릴 수 없습니다. 정말 리셋할까요?'))return;update(d=>({...d,sessions:{},missionLogs:{}}));notify('라운드 미션 기록을 초기화했어요')};return <div className="control-panel"><div className="panel-title"><span><BarChart3/> SCORE CONTROL</span><b>라운드 점수판</b></div><div className="status-controls">{[['waiting','대기'],['active','진행'],['done','완료']].map(([id,label])=><button key={id} className={data.status===id?'active':''} onClick={()=>update(d=>({...d,status:id}))}>{label}</button>)}</div><div className="team-control-grid">{pair.map(t=><TeamControl key={t.id} team={t} booth={booth} data={data} local={local} setLocal={setLocal} cats={cats} setScore={setScore} bump={bump} update={update}/>)}</div><button className="primary wide score-save" onClick={persist}><Check/> 점수판 저장</button><button className="mission-reset-all" onClick={resetMissions}><Trash2/>이 라운드 미션 전체 리셋</button></div>}

function TeamControl({team,booth,data,local,setLocal,cats,setScore,bump,update}){return <section className="team-control" style={{'--team':team.color}}><header><i/><b>{team.name}</b><strong>{teamScore(local.scores,team.id,cats)}점</strong></header><div className="team-score-list">{cats.map(c=><div className="score-stepper" key={c.id}><span>{c.label}<small> / {c.max}</small></span><div><button type="button" onClick={()=>bump(team.id,c,-1)}>−</button><input type="number" inputMode="numeric" min="0" max={c.max} value={local.scores[team.id]?.[c.id]??0} onChange={e=>setScore(team.id,c,e.target.value)}/><button type="button" onClick={()=>bump(team.id,c,1)}>+</button></div></div>)}</div><div className="field"><label><Medal/> MVP 학생</label><input value={local.mvps[team.id]||''} onChange={e=>setLocal(v=>({...v,mvps:{...v.mvps,[team.id]:e.target.value}}))} placeholder={`${team.name} MVP 이름`}/></div><div className="field"><label><NotebookPen/> 특이사항</label><textarea value={local.notesByTeam[team.id]||''} onChange={e=>setLocal(v=>({...v,notesByTeam:{...v.notesByTeam,[team.id]:e.target.value}}))} placeholder={`${team.name} 특이사항`}/></div><MissionLog team={team} booth={booth} data={data} update={update}/></section>}

function MissionLog({team,booth,data,update}){const logs=data.missionLogs?.[team.id]||[];const remove=(id,index)=>{if(!confirm('이 미션·아이템 기록을 삭제하시겠습니까?'))return;if(!confirm('정말 삭제할까요?'))return;update(d=>({...d,missionLogs:{...d.missionLogs,[team.id]:(d.missionLogs?.[team.id]||[]).filter((x,i)=>x.id?x.id!==id:i!==index)}}))};return <div className="team-missions"><h4><Sparkles/> 수행 완료 미션 · 아이템</h4>{!logs.length?<p className="no-log">아직 수행 완료 기록이 없습니다.</p>:logs.map((log,i)=>{const m=booth.missions.find(x=>x.id===log.missionId),item=booth.items.find(x=>x.id===log.itemId);return <div className="mission-log" key={log.id||i}><span><b>{m?.title||'미션'}</b><small>{item?`🎁 ${item.title}`:'아이템 없음'}</small></span><button onClick={()=>remove(log.id||'',i)} aria-label="기록 삭제"><X/></button></div>})}</div>}

function MissionBoard({booth,round,data,update,notify}){const [teamId,setTeamId]=useState(round.teams[0]),[rolling,setRolling]=useState(false),[opening,setOpening]=useState(false);useEffect(()=>setTeamId(round.teams[0]),[round.id]);const team=teamById[teamId],session=data.sessions?.[teamId]||{},logs=data.missionLogs?.[teamId]||[],preset=data.missionPresets?.[teamId]||{},usedMissions=new Set(logs.map(x=>x.missionId)),usedItems=new Set(logs.map(x=>x.itemId)),mission=booth.missions.find(m=>m.id===session.missionId),item=booth.items.find(i=>i.id===session.itemId);const drawMission=()=>{if(rolling||data.status!=='active')return;const available=booth.missions.filter(x=>!usedMissions.has(x.id));if(!available.length){notify('모든 미션을 완료했어요!');return}setRolling(true);setTimeout(()=>{const selected=available.find(x=>x.id===preset.missionId)||available[Math.floor(Math.random()*available.length)];update(d=>({...d,sessions:{...d.sessions,[teamId]:{missionId:selected.id,drawnAt:Date.now()}}}));setRolling(false)},1400)};const openBox=()=>{const available=booth.items.filter(x=>!usedItems.has(x.id));if(!available.length){notify('모든 아이템을 획득했어요!');return}setOpening(true);setTimeout(()=>{const won=available.find(x=>x.id===preset.itemId)||weighted(available),entry={id:`draw-${Date.now()}`,missionId:session.missionId,itemId:won.id,awardedAt:Date.now()};update(d=>({...d,sessions:{...d.sessions,[teamId]:{...entry,logged:true}},missionLogs:{...d.missionLogs,[teamId]:[...(d.missionLogs?.[teamId]||[]),entry]},missionPresets:{...d.missionPresets,[teamId]:{}}}));setOpening(false);notify('미션 완료! 아이템을 획득했어요!')},1700)};return <div className="student-panel" style={{'--team':team.color}}><div className="team-switch">{round.teams.map(id=><button className={teamId===id?'active':''} key={id} style={{'--team':teamById[id].color}} onClick={()=>setTeamId(id)}><i/>{teamById[id].name}</button>)}</div><div className="student-stage"><p className="eyebrow">PLAYER MISSION BOARD</p><h2>{team.name} 탐험대</h2>{!session.missionId?<button type="button" className={`holo-card clickable ${rolling?'rolling':''}`} disabled={rolling||data.status!=='active'} onClick={drawMission}><div><Sparkles/><b>{rolling?'미션 탐색 중…':data.status==='active'?'랜덤 미션 카드':'진행중인 라운드가 없습니다'}</b><small>{preset.missionId?'선생님이 다음 미션을 준비했어요':data.status==='active'?'카드를 터치해 보세요':'점수판에서 라운드를 시작해 주세요'}</small></div></button>:<MissionCard mission={mission}/>} {session.missionId&&!session.itemId&&<button className={`loot-box ${opening?'opening':''}`} onClick={openBox} disabled={opening}><Gift/><b>{opening?'별빛 에너지 충전 중…':'미션 완료 · 아이템 상자 열기'}</b><small>미션을 수행한 뒤 터치하세요</small></button>}{item&&<ItemReveal item={item} used={session.used}/>} {session.itemId&&<button className="secondary" onClick={()=>update(d=>({...d,sessions:{...d.sessions,[teamId]:{}}}))}><RefreshCw/> 다음 미션 준비</button>}</div></div>}

function Admin({live,save,setRoute,notify}){const [tab,setTab]=useState('dashboard'),[game,setGame]=useState('A'),[resetPin,setResetPin]=useState('');const reset=(scope,type)=>{const label=scope==='all'?'전체 게임':`게임 ${scope}`;if(!confirm(`${label}의 ${type==='score'?'점수':'미션'} 기록을 리셋할까요?`))return;if(!confirm('이 작업은 되돌릴 수 없습니다. 정말 진행할까요?'))return;const next=clone(live);const targets=scope==='all'?booths.map(b=>b.id):[scope];for(const id of targets){next.booths??={};next.booths[id]??={};for(const r of booths.find(b=>b.id===id).rounds){const d={...defaultRound,...next.booths[id][r.id]};if(type==='score'){d.scores={};d.mvp='';d.mvpTeam='';d.mvps={};d.notes='';d.notesByTeam={}}else{d.sessions={};d.missionLogs={}}next.booths[id][r.id]=d}}save(next);notify(`${label} ${type==='score'?'점수':'미션'} 기록을 초기화했어요`)};const resetAll=()=>{if(resetPin!=='1111')return;if(!confirm('점수, 미션, MVP, 상태, 변경 시간을 모두 초기화할까요?'))return;if(!confirm('전체 운영 데이터가 삭제됩니다. 정말 초기화할까요?'))return;save(clone(emptyState));setResetPin('');notify('전체 운영 데이터를 초기화했어요')};const toggleMove=()=>{save({...clone(live),moveAlert:!live.moveAlert});notify(`이동 알람을 ${live.moveAlert?'껐어요':'켰어요'}`)};return <section className="admin-page shell"><nav className="topnav"><button className="icon-btn" onClick={()=>setRoute({page:'home'})}><ArrowLeft/></button><div><span>MASTER CONTROL</span><b>운영 관리자</b></div><span className="admin-crown"><Crown/></span></nav><div className="admin-tabs four"><button className={tab==='dashboard'?'active':''} onClick={()=>setTab('dashboard')}><LayoutDashboard/>대시보드</button><button className={tab==='score'?'active':''} onClick={()=>setTab('score')}><Trophy/>점수판</button><button className={tab==='mission'?'active':''} onClick={()=>setTab('mission')}><Rocket/>미션판</button><button className={tab==='mvp'?'active':''} onClick={()=>setTab('mvp')}><Medal/>MVP</button></div>{['score','mission'].includes(tab)&&<div className="admin-games">{booths.map(b=><button key={b.id} className={game===b.id?'active':''} style={{'--accent':b.accent}} onClick={()=>setGame(b.id)}>{b.id}</button>)}</div>}{tab==='dashboard'?<AdminDashboard live={live} save={save} notify={notify}/>:tab==='score'?<AdminScores live={live} game={game} reset={reset}/>:tab==='mission'?<AdminMissions live={live} game={game} reset={reset} save={save} notify={notify}/>:<AdminMvp live={live}/>}<section className="move-control"><div><b>이동 알람 키기</b><span>ON으로 설정하면 모든 게임 점수판에 이동 안내가 표시됩니다.</span></div><button className={live.moveAlert?'on':''} onClick={toggleMove}><i/>{live.moveAlert?'ON':'OFF'}</button></section><section className="full-reset guarded"><div><b>전체 운영 데이터 리셋</b><span>점수 · 미션 · MVP · 라운드 상태 · 변경 시간을 초기값으로 되돌립니다.</span><input type="password" inputMode="numeric" maxLength="4" value={resetPin} onChange={e=>setResetPin(e.target.value)} placeholder="비밀번호 4자리 입력"/></div><button disabled={resetPin!=='1111'} onClick={resetAll}><Trash2/>전체 리셋</button></section></section>}

function AdminScores({live,game,reset}){const gameRanks=rankForGame(live,game),overall=rankOverall(live);return <div className="admin-content"><Ranking title={`게임 ${game} 실시간 랭킹`} rows={gameRanks}/><Ranking title="전체 합산 랭킹" rows={overall}/><div className="reset-zone"><button onClick={()=>reset(game,'score')}><Trash2/>게임 {game} 점수 리셋</button><button className="danger" onClick={()=>reset('all','score')}><Trash2/>전체 점수 리셋</button></div></div>}
function AdminMissions({live,game,reset,save,notify}){const [view,setView]=useState('status'),booth=booths.find(b=>b.id===game),stats=teams.map(t=>{let missions=0,items=0;for(const r of booth.rounds){const d=live.booths?.[game]?.[r.id],logs=d?.missionLogs?.[t.id]||[],current=d?.sessions?.[t.id];missions+=logs.length+(current?.missionId&&!current?.logged?1:0);items+=logs.filter(x=>x.itemId).length+(current?.itemId&&!current?.logged?1:0)}return {...t,missions,items}}).filter(x=>x.missions);return <div className="admin-content"><div className="mission-admin-tabs"><button className={view==='status'?'active':''} onClick={()=>setView('status')}>수행 현황</button><button className={view==='preset'?'active':''} onClick={()=>setView('preset')}>프리셋 설정</button></div>{view==='status'?<><section className="admin-card"><h2>게임 {game} 미션 수행 현황</h2>{!stats.length?<div className="empty"><Orbit/><p>아직 수행한 미션이 없습니다.</p></div>:stats.map(s=><div className="mission-stat simple" key={s.id} style={{'--team':s.color}}><i/><b>{s.name}</b><span>미션 {s.missions}</span><span>아이템 {s.items}</span></div>)}</section><div className="reset-zone"><button onClick={()=>reset(game,'mission')}><Trash2/>게임 {game} 미션 리셋</button><button className="danger" onClick={()=>reset('all','mission')}><Trash2/>전체 미션 리셋</button></div></>:<AdminPresets live={live} booth={booth} save={save} notify={notify}/>}</div>}

function AdminPresets({live,booth,save,notify}){const [roundId,setRoundId]=useState(booth.rounds[0].id),[draft,setDraft]=useState({});useEffect(()=>{setRoundId(booth.rounds[0].id)},[booth.id]);useEffect(()=>{setDraft(clone(live.booths?.[booth.id]?.[roundId]?.missionPresets||{}))},[booth.id,roundId,JSON.stringify(live.booths?.[booth.id]?.[roundId]?.missionPresets)]);const round=booth.rounds.find(r=>r.id===roundId),status=live.booths?.[booth.id]?.[roundId]?.status||'waiting',locked=status!=='waiting';const setField=(teamId,key,value)=>setDraft(v=>({...v,[teamId]:{...v[teamId],[key]:value}}));const persist=()=>{if(locked)return;const next=clone(live);next.booths??={};next.booths[booth.id]??={};next.booths[booth.id][roundId]={...defaultRound,...next.booths[booth.id][roundId],missionPresets:draft};save(next);notify(`게임 ${booth.id} ${round.label} 프리셋을 저장했어요`)};return <section className="admin-card preset-admin"><h2>게임 {booth.id} 사전 프리셋</h2><p>설정하지 않은 항목은 기존 가중치에 따라 랜덤으로 결정됩니다.</p><div className="preset-rounds">{booth.rounds.map(r=><button key={r.id} className={roundId===r.id?'active':''} onClick={()=>setRoundId(r.id)}>{r.label}</button>)}</div>{locked&&<div className="preset-lock"><LockKeyhole/> {round.label}이 {status==='active'?'진행중':'완료'} 상태라 수정할 수 없습니다.</div>}<div className="preset-team-grid">{round.teams.map(teamId=>{const team=teamById[teamId],value=draft[teamId]||{};return <article key={teamId} style={{'--team':team.color}}><h3><i/>{team.name}</h3><label>미션<select disabled={locked} value={value.missionId||''} onChange={e=>setField(teamId,'missionId',e.target.value)}><option value="">설정 안 함 · 랜덤</option>{booth.missions.map(m=><option key={m.id} value={m.id}>{m.title}</option>)}</select></label><label>아이템<select disabled={locked} value={value.itemId||''} onChange={e=>setField(teamId,'itemId',e.target.value)}><option value="">설정 안 함 · 랜덤</option>{booth.items.map(i=><option key={i.id} value={i.id}>{i.title}</option>)}</select></label></article>})}</div><button className="primary wide" disabled={locked} onClick={persist}><Check/> 프리셋 저장</button></section>}
function AdminMvp({live}){const entries=[];for(const booth of booths)for(const round of booth.rounds){const data=live.booths?.[booth.id]?.[round.id],mvps={...data?.mvps},notes={...data?.notesByTeam};if(data?.mvp&&data?.mvpTeam&&!mvps[data.mvpTeam])mvps[data.mvpTeam]=data.mvp;if(data?.notes&&!Object.values(notes).some(Boolean))for(const id of round.teams)notes[id]=data.notes;for(const teamId of round.teams){if(!mvps[teamId]&&!notes[teamId])continue;entries.push({key:`${booth.id}-${round.id}-${teamId}`,game:`게임 ${booth.id} · ${booth.short}`,round:round.label,team:teamById[teamId]?.name,name:mvps[teamId]||'MVP 미입력',notes:notes[teamId]||'기타 기록 없음',color:teamById[teamId]?.color})}}return <div className="admin-content"><section className="admin-card mvp-list"><h2>MVP · 기타 기록</h2>{!entries.length?<div className="empty"><Medal/><p>아직 저장된 MVP 또는 기타 기록이 없습니다.</p></div>:entries.map((e,i)=><article className="mvp-entry" key={e.key} style={{'--team':e.color}}><div className="mvp-order">{i+1}</div><div><span>{e.game} · {e.round}</span><h3><Medal/> {e.name}</h3><b>{e.team}</b><p>{e.notes}</p></div></article>)}</section></div>}

function AdminDashboard({live,save,notify}){const defaults=Object.fromEntries(booths[0].rounds.map(r=>[r.id,r.time]));for(const br of scheduleBreaks)defaults[br.id]=br.time;const [times,setTimes]=useState({...defaults,...live.scheduleTimes}),[locations,setLocations]=useState({...live.gameLocations});useEffect(()=>setTimes({...defaults,...live.scheduleTimes}),[JSON.stringify(live.scheduleTimes)]);useEffect(()=>setLocations({...live.gameLocations}),[JSON.stringify(live.gameLocations)]);const statusLabel=s=>s==='active'?'진행중':s==='done'?'완료':'대기중';const gameStatus=booth=>{const states=booth.rounds.map(r=>live.booths?.[booth.id]?.[r.id]?.status||'waiting');return states.includes('active')?'active':states.every(s=>s==='done')?'done':'waiting'};const rows=[booths[0].rounds[0],booths[0].rounds[1],...scheduleBreaks,booths[0].rounds[2],booths[0].rounds[3]];const persistTimes=()=>{save({...clone(live),scheduleTimes:times});notify('변경 시간을 저장했어요')},persistLocations=()=>{save({...clone(live),gameLocations:locations});notify('게임 장소를 저장했어요')};return <div className="admin-content dashboard"><section className="admin-card"><h2>게임 현재 상태</h2><div className="game-status-grid">{booths.map(b=>{const s=gameStatus(b);return <div key={b.id} className={`game-status ${s}`} style={{'--accent':b.accent}}><b>GAME {b.id}</b><span>{statusLabel(s)}</span></div>})}</div></section><section className="admin-card schedule-card"><h2>운영 시간표</h2><p className="schedule-help">왼쪽 시간 칸을 눌러 직접 수정할 수 있습니다.</p><div className="schedule-scroll"><div className="schedule-grid"><div className="schedule-corner">시간</div>{booths.map(b=><b key={b.id}>GAME {b.id}</b>)}{rows.map(row=><ScheduleRow key={row.id} row={row} live={live} times={times} setTimes={setTimes}/>)}</div></div><button className="primary wide schedule-save" onClick={persistTimes}><Check/> 변경 시간 저장</button><div className="location-block"><div><h3>게임 장소</h3><p>당일 장소를 입력하면 팀 이동 안내에 자동으로 표시됩니다.</p></div><div className="location-grid">{booths.map(b=><label key={b.id} style={{'--accent':b.accent}}><span>GAME {b.id}<small>{b.title}</small></span><input value={locations[b.id]||''} onChange={e=>setLocations(v=>({...v,[b.id]:e.target.value}))} placeholder="장소 입력"/></label>)}</div><button className="secondary location-save" onClick={persistLocations}><Check/> 게임 장소 저장</button></div></section></div>}
function ScheduleRow({row,live,times,setTimes}){const isBreak=!row.teams&&row.id==='snack';return <><div className="schedule-time"><b>{row.label}</b><input aria-label={`${row.label} 시간`} value={times[row.id]||''} onChange={e=>setTimes(v=>({...v,[row.id]:e.target.value}))} placeholder="09:10–09:40"/></div>{booths.map(b=>{if(isBreak)return <div key={b.id} className="schedule-cell break"><span>간식</span></div>;const s=live.booths?.[b.id]?.[row.id]?.status||'waiting';return <div key={b.id} className={`schedule-cell ${s}`}><span>{s==='active'?'진행중':s==='done'?'완료':'대기중'}</span><small>{b.rounds.find(r=>r.id===row.id).teams.map(id=>teamById[id].name).join(' · ')}</small></div>})}</>}
function Ranking({title,rows}){return <section className="admin-card"><h2>{title}</h2>{rows.map((r,i)=><div className="rank-row" key={r.id} style={{'--team':r.color}}><strong>{i+1}</strong><i/><b>{r.name}</b><span>{r.score}점</span></div>)}</section>}
function rankForGame(live,id){const b=booths.find(x=>x.id===id),cats=scoreConfig[id];return teams.map(t=>({...t,score:b.rounds.reduce((n,r)=>n+teamScore(live.booths?.[id]?.[r.id]?.scores,t.id,cats),0)})).sort((a,b)=>b.score-a.score)}
function rankOverall(live){return teams.map(t=>({...t,score:booths.reduce((n,b)=>n+rankForGame(live,b.id).find(x=>x.id===t.id).score,0)})).sort((a,b)=>b.score-a.score)}
function MissionCard({mission}){return <div className="mission-card"><div className="card-top"><span>MISSION {mission.id.padStart(2,'0')}</span></div><div className="mission-symbol"><Star/></div><h3>{mission.title}</h3><p>{mission.description}</p></div>}
function ItemReveal({item,used}){return <div className={`item-reveal ${used?'used':''}`}><span className="rarity">STAR ITEM</span><div className="item-gem"><Gift/></div><p>ITEM {item.id.padStart(2,'0')}</p><h3>{item.title}</h3><div>{item.description}</div>{used&&<em><Check/> 사용 완료</em>}</div>}
function Modal({children,close}){return <div className="modal" onClick={close}><div className="modal-body" onClick={e=>e.stopPropagation()}><button className="modal-close" onClick={close}><X/></button>{children}</div></div>}
function weighted(items){const total=items.reduce((n,i)=>n+i.weight,0);let r=Math.random()*total;return items.find(i=>(r-=i.weight)<=0)||items[0]}
